import type { Listing, Profile } from '@/types'

const now = Date.now()
const h = (n: number) => new Date(now - n * 3600000).toISOString()

export const DEMO_PROFILES: Profile[] = []

const P: Record<string, Profile> = {
  meiLing: {
    id: 'demo-mei',
    username: 'meilingc',
    full_name: 'Mei-Ling C.',
    bio: 'Ex-McKinsey consultant who stopped asking whether the market is big enough. Building stuff I would actually use.',
    avatar_url: null,
    skills: ['AI/ML', 'B2C', 'Product Strategy'],
    location: 'Berlin',
    created_at: h(720),
  },
  tariq: {
    id: 'demo-tariq',
    username: 'tariqb',
    full_name: 'Tariq B.',
    bio: 'Dropped out of 3 universities, 0 exits, infinite energy. My grandma says I should get a real job. She is wrong.',
    avatar_url: null,
    skills: ['Web3', 'Mobile', 'Chaos Engineering'],
    location: 'Hamburg',
    created_at: h(600),
  },
  anastasia: {
    id: 'demo-ana',
    username: 'anastasiak',
    full_name: 'Anastasia K.',
    bio: '15 years in consulting and all I learned was how to pitch. Now learning what building actually means.',
    avatar_url: null,
    skills: ['Operations', 'Enterprise Sales', 'Buzzwords'],
    location: 'München',
    created_at: h(800),
  },
  kofi: {
    id: 'demo-kofi',
    username: 'kofia',
    full_name: 'Kofi A.',
    bio: 'Serial pivot artist. Last three pivots: Metaverse dog salon → NFT bakery → this. This time it will be different.',
    avatar_url: null,
    skills: ['Fundraising', 'Pitching', 'Pivoting'],
    location: 'Frankfurt',
    created_at: h(400),
  },
  carlos: {
    id: 'demo-carlos',
    username: 'carlosr',
    full_name: 'Carlos R.',
    bio: 'I thought I was building the next Uber. It was an app for hedgehogs. This time it really is the next Uber.',
    avatar_url: null,
    skills: ['Marketplace', 'Growth', 'VC Blind Dates'],
    location: 'Zürich',
    created_at: h(500),
  },
  yuki: {
    id: 'demo-yuki',
    username: 'yukit',
    full_name: 'Yuki T.',
    bio: 'FOMO-driven builder with ADHD. 4th startup idea this week, 3rd last week. We will find one that sticks.',
    avatar_url: null,
    skills: ['React Native', 'Rapid Prototyping', 'Sleep Deprivation'],
    location: 'Remote',
    created_at: h(350),
  },
  lena: {
    id: 'demo-lena',
    username: 'lenam',
    full_name: 'Lena M.',
    bio: 'Psychologist who read too much Twilight and is now building AI for emotional support. Yes, really.',
    avatar_url: null,
    skills: ['Psychology', 'UX Research', 'Empathy-as-a-Service'],
    location: 'Leipzig',
    created_at: h(480),
  },
  felix: {
    id: 'demo-felix',
    username: 'felixw',
    full_name: 'Felix W.',
    bio: 'Backend engineer who after 8 years of Google salary finally wants to build something meaningful. Or at least funny.',
    avatar_url: null,
    skills: ['Go', 'Kubernetes', 'Existential Crisis'],
    location: 'Berlin',
    created_at: h(200),
  },
  priya: {
    id: 'demo-priya',
    username: 'priyad',
    full_name: 'Priya D.',
    bio: 'Product Lead at a unicorn nobody likes. Building on the side what I actually want to build.',
    avatar_url: null,
    skills: ['Product', 'User Research', 'Internal Suffering'],
    location: 'Düsseldorf',
    created_at: h(300),
  },
  bjorn: {
    id: 'demo-bjorn',
    username: 'bjornl',
    full_name: 'Björn L.',
    bio: 'Swede in Germany. Cannot deal with the bureaucracy so building software to fight it.',
    avatar_url: null,
    skills: ['FinTech', 'Compliance', 'Sarcasm'],
    location: 'Stuttgart',
    created_at: h(250),
  },
  amara: {
    id: 'demo-amara',
    username: 'amarao',
    full_name: 'Amara O.',
    bio: 'Doctor who realized the healthcare system is broken and decided to fail at fixing it as a founder rather than as a physician.',
    avatar_url: null,
    skills: ['HealthTech', 'Medicine', 'Systems Thinking'],
    location: 'Köln',
    created_at: h(380),
  },
  sven: {
    id: 'demo-sven',
    username: 'svenkr',
    full_name: 'Sven K.',
    bio: 'Founded three startups. Two are dead, one is somehow still alive. Ratio is okay.',
    avatar_url: null,
    skills: ['B2B SaaS', 'Customer Success', 'Resilience'],
    location: 'Hamburg',
    created_at: h(550),
  },
  nina: {
    id: 'demo-nina',
    username: 'ninav',
    full_name: 'Nina V.',
    bio: 'Climate scientist who got tired of writing reports nobody reads. Now building tools that make people actually act on climate data.',
    avatar_url: null,
    skills: ['Climate Tech', 'Data Science', 'Python'],
    location: 'Freiburg',
    created_at: h(420),
  },
  marko: {
    id: 'demo-marko',
    username: 'markon',
    full_name: 'Marko N.',
    bio: 'Ex-pro footballer turned full-stack dev. Spent 5 years in Bundesliga 3, now spending 5 years learning TypeScript. Both are painful.',
    avatar_url: null,
    skills: ['TypeScript', 'React', 'Sports Analytics'],
    location: 'Dortmund',
    created_at: h(310),
  },
  sophie: {
    id: 'demo-sophie',
    username: 'sophiew',
    full_name: 'Sophie W.',
    bio: 'Lawyer who learned to code during lockdown. Now doing both at once which means I am bad at two things simultaneously.',
    avatar_url: null,
    skills: ['LegalTech', 'TypeScript', 'Contract Law'],
    location: 'Frankfurt',
    created_at: h(190),
  },
  ali: {
    id: 'demo-ali',
    username: 'alikh',
    full_name: 'Ali K.',
    bio: 'Refugee turned software architect. Built a fintech in Kabul, escaped in 2021, rebuilt everything from scratch in Berlin. Not stopping.',
    avatar_url: null,
    skills: ['FinTech', 'System Design', 'Resilience'],
    location: 'Berlin',
    created_at: h(160),
  },
  elena: {
    id: 'demo-elena',
    username: 'elenap',
    full_name: 'Elena P.',
    bio: 'Food scientist at Nestlé who realized corporations will never fix food. Building the alternative from a 30m² apartment kitchen.',
    avatar_url: null,
    skills: ['FoodTech', 'Supply Chain', 'Chemistry'],
    location: 'Lausanne',
    created_at: h(440),
  },
  thomas: {
    id: 'demo-thomas',
    username: 'thomask',
    full_name: 'Thomas K.',
    bio: 'Teacher who spent 12 years watching EdTech companies build for investors not students. Done watching.',
    avatar_url: null,
    skills: ['EdTech', 'Pedagogy', 'Curriculum Design'],
    location: 'Wien',
    created_at: h(520),
  },
  zara: {
    id: 'demo-zara',
    username: 'zaraf',
    full_name: 'Zara F.',
    bio: 'Fashion industry insider who is deeply ashamed of it. Building circular economy tools to clean up the mess I helped make.',
    avatar_url: null,
    skills: ['Sustainability', 'Fashion', 'B2B Sales'],
    location: 'München',
    created_at: h(280),
  },
  leon: {
    id: 'demo-leon',
    username: 'leong',
    full_name: 'Leon G.',
    bio: 'Architecture student who realized buildings take 10 years to build and pivoted to software. Both involve a lot of frustration with clients.',
    avatar_url: null,
    skills: ['PropTech', '3D Modeling', 'Figma'],
    location: 'Hamburg',
    created_at: h(130),
  },
}

Object.values(P).forEach(p => DEMO_PROFILES.push(p))

type DemoListing = Omit<Listing, 'profiles'> & {
  profiles: Profile
  seeks_investment?: boolean
  investment_round?: string
}

export const DEMO_LISTINGS: DemoListing[] = [
  {
    id: 'demo-1',
    user_id: 'demo-mei',
    title: 'Tinder for lunch breaks — because introverts need to eat too',
    description: 'Matching algorithm for office workers who don\'t want to eat alone but also have zero small talk energy. AI picks who can compatibly stay silent together. 340 beta users, 12% conversion to actual meetups. The rest just ate alone. That\'s fine too.',
    role_category: 'developer',
    stage: 'mvp',
    compensation_type: 'equity',
    equity_percent: 12,
    is_active: true,
    created_at: h(1),
    updated_at: h(1),
    profiles: P.meiLing,
  },
  {
    id: 'demo-2',
    user_id: 'demo-tariq',
    title: 'Blockchain for allotment garden waitlists',
    description: 'In German cities you wait 15–25 years for an allotment garden. We tokenize waiting spots as NFTs — tradeable, loanable, inheritable. Sounds stupid. 400 people on our own waitlist. Looking for a CTO who doesn\'t immediately say no.',
    role_category: 'cofounder',
    stage: 'idea',
    compensation_type: 'equity',
    equity_percent: 30,
    is_active: true,
    created_at: h(2),
    updated_at: h(2),
    seeks_investment: true,
    investment_round: 'pre-seed',
    profiles: P.tariq,
  },
  {
    id: 'demo-3',
    user_id: 'demo-ana',
    title: 'SaaS CRM for astrologers',
    description: 'There are 180,000 active astrologers in the DACH region. None of them have a proper booking tool. We are building HubSpot but for people who use Mercury retrograde as an excuse for everything. MRR: €8,400. Looking for a designer who gets the vibe.',
    role_category: 'designer',
    stage: 'revenue',
    compensation_type: 'both',
    equity_percent: 7,
    is_active: true,
    created_at: h(3),
    updated_at: h(3),
    profiles: P.anastasia,
  },
  {
    id: 'demo-4',
    user_id: 'demo-kofi',
    title: 'Uber but only for elderly people going to the doctor',
    description: 'My grandma can\'t get to chemo because there\'s no taxi and she can\'t use Uber. Pilot in Frankfurt: 60 elderly users, 94% want to come back. Looking for a co-founder with mobility background or at least empathy.',
    role_category: 'cofounder',
    stage: 'mvp',
    compensation_type: 'equity',
    equity_percent: 20,
    is_active: true,
    created_at: h(4),
    updated_at: h(4),
    seeks_investment: true,
    investment_round: 'seed',
    profiles: P.kofi,
  },
  {
    id: 'demo-5',
    user_id: 'demo-carlos',
    title: 'AI writes your apologies for every situation in life',
    description: 'GPT-4 generates convincing apologies for: being late, forgetting birthdays, ignoring WhatsApp, skipping the gym, and lying to your boss. 50k downloads, 4.8 stars. "Life-saving" — App Store review. Looking for a growth hacker with as little shame as we have.',
    role_category: 'marketing',
    stage: 'revenue',
    compensation_type: 'both',
    equity_percent: 9,
    is_active: true,
    created_at: h(5),
    updated_at: h(5),
    profiles: P.carlos,
  },
  {
    id: 'demo-6',
    user_id: 'demo-yuki',
    title: 'RentTok — TikTok for seniors, font size 24, no algorithm stress',
    description: 'My grandma needed 4 hours to understand TikTok. We\'re building the same thing but without content that pushes after 9pm. 200 beta grandmas. One said "better than TV". We\'re using that as a testimonial.',
    role_category: 'developer',
    stage: 'mvp',
    compensation_type: 'equity',
    equity_percent: 18,
    is_active: true,
    created_at: h(7),
    updated_at: h(7),
    profiles: P.yuki,
  },
  {
    id: 'demo-7',
    user_id: 'demo-lena',
    title: 'Therapy app for founders who believe their own pitch',
    description: 'CBT combined with reality checks for founder brains. Module 1: "No, your idea is not the next Google." Module 2: "Your investor update is not a success." 1,200 founders on the waitlist. Need a backend dev who might need therapy themselves.',
    role_category: 'developer',
    stage: 'idea',
    compensation_type: 'equity',
    equity_percent: 22,
    is_active: true,
    created_at: h(9),
    updated_at: h(9),
    profiles: P.lena,
  },
  {
    id: 'demo-8',
    user_id: 'demo-tariq',
    title: 'DAO for allotment gardeners — finally DeFi for boomers',
    description: 'German gardening clubs collectively hold €2.3B in land but have zero digital infrastructure. Token voting for "who can plant leek next to tomatoes" decisions. Pilot with 3 clubs. Looking for someone who understands both Solidity and gardening law.',
    role_category: 'cofounder',
    stage: 'mvp',
    compensation_type: 'equity',
    equity_percent: 25,
    is_active: true,
    created_at: h(11),
    updated_at: h(11),
    seeks_investment: true,
    investment_round: 'pre-seed',
    profiles: P.tariq,
  },
  {
    id: 'demo-9',
    user_id: 'demo-ana',
    title: 'B2B API for German government forms — Stripe for bureaucracy',
    description: 'All German administrative forms as an API. Sounds boring. €40k MRR after 8 months, zero marketing. Enterprise clients pay because they have no alternative. Looking for a sales person who doesn\'t hate bureaucracy.',
    role_category: 'sales',
    stage: 'revenue',
    compensation_type: 'both',
    equity_percent: 8,
    is_active: true,
    created_at: h(14),
    updated_at: h(14),
    profiles: P.anastasia,
  },
  {
    id: 'demo-10',
    user_id: 'demo-felix',
    title: 'Duolingo but for tax returns',
    description: '5-minute lessons explaining what a depreciation allowance is, why you can deduct your office chair, and what "extraordinary burden" actually means. 15k users, 40% now do their taxes themselves. The tax software lobby is not happy. Good sign.',
    role_category: 'marketing',
    stage: 'mvp',
    compensation_type: 'both',
    equity_percent: 10,
    is_active: true,
    created_at: h(16),
    updated_at: h(16),
    profiles: P.felix,
  },
  {
    id: 'demo-11',
    user_id: 'demo-priya',
    title: 'Anonymous Glassdoor but founders review their investors',
    description: 'Investors can read everything about startups but founders can\'t see which VC takes 6 months to say no. We built that. 800 verified reviews in beta. No VC has complained yet because they haven\'t found it.',
    role_category: 'developer',
    stage: 'mvp',
    compensation_type: 'equity',
    equity_percent: 15,
    is_active: true,
    created_at: h(20),
    updated_at: h(20),
    profiles: P.priya,
  },
  {
    id: 'demo-12',
    user_id: 'demo-bjorn',
    title: 'AI assistant that translates German bureaucratic language into German',
    description: 'A "Mahnbescheid" is not a description of someone who nags. We translate government German into language humans understand, in real-time via browser extension. 12k active users. The relevant ministries have asked questions. We replied politely.',
    role_category: 'cofounder',
    stage: 'mvp',
    compensation_type: 'equity',
    equity_percent: 30,
    is_active: true,
    created_at: h(24),
    updated_at: h(24),
    profiles: P.bjorn,
  },
  {
    id: 'demo-13',
    user_id: 'demo-amara',
    title: 'Waiting room killer for doctor\'s offices — Tetris for the waiting room',
    description: 'Patients wait an average of 43 minutes. We replace 2019 magazines with a tablet showing health explainer videos, prevention checklists and games. 25 practices in pilot. Doctors say "finally". Patients say "already my turn". Looking for a developer.',
    role_category: 'developer',
    stage: 'mvp',
    compensation_type: 'both',
    equity_percent: 13,
    is_active: true,
    created_at: h(30),
    updated_at: h(30),
    seeks_investment: true,
    investment_round: 'seed',
    profiles: P.amara,
  },
  {
    id: 'demo-14',
    user_id: 'demo-sven',
    title: 'Slack but for tradespeople — no English, no threads',
    description: 'My dad is an electrician. He uses WhatsApp for everything including quotes and complaints. We\'re building an app that looks like WhatsApp but is GDPR-compliant and has quotes, reports and timesheets. 40 businesses are already paying.',
    role_category: 'cofounder',
    stage: 'revenue',
    compensation_type: 'equity',
    equity_percent: 20,
    is_active: true,
    created_at: h(36),
    updated_at: h(36),
    profiles: P.sven,
  },
  {
    id: 'demo-15',
    user_id: 'demo-felix',
    title: 'Automated code review but for tax returns',
    description: 'We process ELSTER exports and automatically find errors, forgotten deductions and places you can legally save money. Closed beta, 200 tax advisors. Looking for someone who doesn\'t shut down when they hear "data protection" but leans in.',
    role_category: 'designer',
    stage: 'idea',
    compensation_type: 'equity',
    equity_percent: 17,
    is_active: true,
    created_at: h(42),
    updated_at: h(42),
    profiles: P.felix,
  },
  {
    id: 'demo-16',
    user_id: 'demo-kofi',
    title: 'On-demand storage for Berliners without a cellar',
    description: 'Airbnb for basement storage. Berlin apartments have no cellar. Berliners have too much stuff. We match the two. 180 active listings in Berlin, 60% occupancy. Looking for a marketing person who can explain why this isn\'t weird.',
    role_category: 'marketing',
    stage: 'mvp',
    compensation_type: 'both',
    equity_percent: 11,
    is_active: true,
    created_at: h(48),
    updated_at: h(48),
    profiles: P.kofi,
  },
  {
    id: 'demo-17',
    user_id: 'demo-priya',
    title: 'AI coach that tells you when to stop working',
    description: 'Not another productivity app. The opposite of that. Detects burnout patterns from calendar + Slack activity and sends you a message at 6:30pm: "Stop now." 3,000 users, 22% fewer overtime hours by self-report. HR teams find this alarming.',
    role_category: 'developer',
    stage: 'mvp',
    compensation_type: 'equity',
    equity_percent: 14,
    is_active: true,
    created_at: h(55),
    updated_at: h(55),
    profiles: P.priya,
  },
  {
    id: 'demo-18',
    user_id: 'demo-yuki',
    title: 'Fiverr but only for things retirees can do',
    description: 'Marketplace for skills over 65: fix a typewriter, read old German script, bake real bread, fill in tax forms without software. Irony: mostly used by Gen Z. 420 active providers. Looking for a co-founder who can take this seriously without laughing.',
    role_category: 'cofounder',
    stage: 'mvp',
    compensation_type: 'equity',
    equity_percent: 28,
    is_active: true,
    created_at: h(65),
    updated_at: h(65),
    profiles: P.yuki,
  },
  {
    id: 'demo-19',
    user_id: 'demo-bjorn',
    title: 'Tinder for tax advisors and freelancers',
    description: 'Finding the right tax advisor is like dating. Profile matching by industry, communication style and whether you prefer WhatsApp or email. 2,000 successful matches. 0 lawsuits so far. Looking for a backend dev.',
    role_category: 'developer',
    stage: 'revenue',
    compensation_type: 'both',
    equity_percent: 6,
    is_active: true,
    created_at: h(72),
    updated_at: h(72),
    profiles: P.bjorn,
  },
  {
    id: 'demo-20',
    user_id: 'demo-amara',
    title: 'Health tracking that doesn\'t pretend you\'re an athlete',
    description: 'Every fitness app assumes you do 10,000 steps and wake up at 6am. We track whether you drank your water bottle, went outside today and didn\'t spend four hours on TikTok. Pilot: 800 users with explicitly low goals. 67% feel better.',
    role_category: 'designer',
    stage: 'mvp',
    compensation_type: 'equity',
    equity_percent: 16,
    is_active: true,
    created_at: h(80),
    updated_at: h(80),
    profiles: P.amara,
  },
  // New listings
  {
    id: 'demo-21',
    user_id: 'demo-nina',
    title: 'Carbon footprint tracker that doesn\'t make you feel guilty every time',
    description: 'Every climate app shows you a red number and then leaves you alone with it. We calculate your footprint and show you the three cheapest changes you can actually make this week. 2,400 users, avg carbon reduction 18% in 3 months. Need a product designer.',
    role_category: 'designer',
    stage: 'mvp',
    compensation_type: 'both',
    equity_percent: 12,
    is_active: true,
    created_at: h(6),
    updated_at: h(6),
    profiles: P.nina,
  },
  {
    id: 'demo-22',
    user_id: 'demo-marko',
    title: 'Video analysis platform for amateur football coaches',
    description: 'Pro clubs have Wyscout. Sunday league coaches have nothing. We built automatic video tagging, player heatmaps and tactical boards for €29/month. 600 clubs paying. Bundesliga 3 clubs asking about whitelabeling. Need a backend engineer.',
    role_category: 'developer',
    stage: 'revenue',
    compensation_type: 'both',
    equity_percent: 10,
    is_active: true,
    created_at: h(8),
    updated_at: h(8),
    seeks_investment: true,
    investment_round: 'seed',
    profiles: P.marko,
  },
  {
    id: 'demo-23',
    user_id: 'demo-sophie',
    title: 'Legal contract review AI for freelancers who can\'t afford a lawyer',
    description: 'Freelancers sign contracts without reading them because lawyers cost €300/hr. We scan any contract in German, flag the dangerous clauses and explain them in plain language. 8k freelancers, €19/month. Big law firms haven\'t noticed yet.',
    role_category: 'marketing',
    stage: 'revenue',
    compensation_type: 'both',
    equity_percent: 8,
    is_active: true,
    created_at: h(10),
    updated_at: h(10),
    profiles: P.sophie,
  },
  {
    id: 'demo-24',
    user_id: 'demo-ali',
    title: 'Banking for the unbanked in Europe — refugees and migrants first',
    description: '15M people in Europe have no bank account. Not because they don\'t want one. Because the KYC process was designed for someone with a German address and a Schufa score. We built an alternative. 3,200 active accounts, 0 fraud cases. Raising seed.',
    role_category: 'cofounder',
    stage: 'revenue',
    compensation_type: 'equity',
    equity_percent: 15,
    is_active: true,
    created_at: h(12),
    updated_at: h(12),
    seeks_investment: true,
    investment_round: 'seed',
    profiles: P.ali,
  },
  {
    id: 'demo-25',
    user_id: 'demo-elena',
    title: 'Ugly vegetable subscription box — the supermarket rejects',
    description: 'German supermarkets reject 30% of vegetables for aesthetic reasons. We buy them directly from farmers and deliver them. €23/box, 1,400 subscribers, 100% month-on-month growth for 6 months. Need a co-founder to handle everything I am bad at.',
    role_category: 'cofounder',
    stage: 'revenue',
    compensation_type: 'equity',
    equity_percent: 25,
    is_active: true,
    created_at: h(15),
    updated_at: h(15),
    profiles: P.elena,
  },
  {
    id: 'demo-26',
    user_id: 'demo-thomas',
    title: 'Homework help AI that teaches instead of giving answers',
    description: 'ChatGPT does the homework. We make the AI Socratic — it asks questions until the student figures it out themselves. Teachers love it. Students are annoyed by it. That means it works. 4,000 students, 90 schools piloting. Need a React developer.',
    role_category: 'developer',
    stage: 'mvp',
    compensation_type: 'both',
    equity_percent: 14,
    is_active: true,
    created_at: h(18),
    updated_at: h(18),
    profiles: P.thomas,
  },
  {
    id: 'demo-27',
    user_id: 'demo-zara',
    title: 'Resale infrastructure for fashion brands — returns become revenue',
    description: 'Fashion brands send 30% of returns to landfill because resale is too complex. We built a white-label resale platform they can embed. 12 mid-size brands live, €180k GMV last month. Need a head of partnerships who knows fashion.',
    role_category: 'sales',
    stage: 'revenue',
    compensation_type: 'both',
    equity_percent: 9,
    is_active: true,
    created_at: h(21),
    updated_at: h(21),
    seeks_investment: true,
    investment_round: 'series-a',
    profiles: P.zara,
  },
  {
    id: 'demo-28',
    user_id: 'demo-leon',
    title: '3D apartment configurator for renters before they sign',
    description: 'You sign a lease for a flat you\'ve seen once for 20 minutes. We let you walk through a 3D model, place your furniture and see if your IKEA couch fits before you commit. 40 real estate agencies, 12k flat viewings replaced. Need a backend engineer.',
    role_category: 'developer',
    stage: 'mvp',
    compensation_type: 'equity',
    equity_percent: 20,
    is_active: true,
    created_at: h(25),
    updated_at: h(25),
    profiles: P.leon,
  },
  {
    id: 'demo-29',
    user_id: 'demo-nina',
    title: 'Real-time air quality monitor for schools',
    description: 'CO2 levels above 1,500ppm destroy concentration. Most classrooms hit 2,500ppm by 10am. We install a €49 sensor, it auto-opens the window reminder and logs data for parents. 200 schools, Munich is mandating it district-wide. Need growth.',
    role_category: 'marketing',
    stage: 'revenue',
    compensation_type: 'both',
    equity_percent: 7,
    is_active: true,
    created_at: h(28),
    updated_at: h(28),
    profiles: P.nina,
  },
  {
    id: 'demo-30',
    user_id: 'demo-marko',
    title: 'Injury prediction model for youth athletes',
    description: 'ACL injuries peak at 14-16. We analyze movement patterns from training video and flag biomechanical red flags 3-6 months before injury. Pilot with 8 academies. 0 flagged athletes have been injured. 2 unflagged ones have. The model works.',
    role_category: 'cofounder',
    stage: 'mvp',
    compensation_type: 'equity',
    equity_percent: 30,
    is_active: true,
    created_at: h(32),
    updated_at: h(32),
    seeks_investment: true,
    investment_round: 'pre-seed',
    profiles: P.marko,
  },
  {
    id: 'demo-31',
    user_id: 'demo-sophie',
    title: 'Automated GDPR compliance for SaaS startups',
    description: 'Every SaaS founder knows they should do GDPR properly. None of them do because lawyers want €5k upfront. We scan your codebase and data flows, generate the documentation automatically and keep it updated. 350 startups, €89/month. Looking for a developer co-founder.',
    role_category: 'cofounder',
    stage: 'revenue',
    compensation_type: 'equity',
    equity_percent: 22,
    is_active: true,
    created_at: h(38),
    updated_at: h(38),
    profiles: P.sophie,
  },
  {
    id: 'demo-32',
    user_id: 'demo-ali',
    title: 'Cross-border remittance for DACH diaspora communities',
    description: 'Western Union charges 8% to send money home. We charge 0.5%. Onboarding works with a passport photo, no German ID needed. €2.1M transferred in first 4 months. Zero chargebacks. Licensing in progress. Need a compliance co-founder.',
    role_category: 'cofounder',
    stage: 'revenue',
    compensation_type: 'equity',
    equity_percent: 18,
    is_active: true,
    created_at: h(45),
    updated_at: h(45),
    seeks_investment: true,
    investment_round: 'seed',
    profiles: P.ali,
  },
  {
    id: 'demo-33',
    user_id: 'demo-elena',
    title: 'B2B fermentation-as-a-service for food brands',
    description: 'Fermentation is the next big food trend but it requires specialist knowledge. We license our fermentation IP and provide toll-manufacturing for brands who want to add kombucha, kefir or kimchi to their line without the complexity. 6 brand clients, €340k ARR.',
    role_category: 'sales',
    stage: 'revenue',
    compensation_type: 'both',
    equity_percent: 10,
    is_active: true,
    created_at: h(52),
    updated_at: h(52),
    profiles: P.elena,
  },
  {
    id: 'demo-34',
    user_id: 'demo-thomas',
    title: 'Language learning app built around real news stories',
    description: 'Duolingo teaches you "the duck is under the table". Real language learners want to read the news. We take actual news articles and break them down to your level, track vocabulary and adjust difficulty. 18k active learners, 6 languages. Need a designer.',
    role_category: 'designer',
    stage: 'mvp',
    compensation_type: 'both',
    equity_percent: 11,
    is_active: true,
    created_at: h(58),
    updated_at: h(58),
    profiles: P.thomas,
  },
  {
    id: 'demo-35',
    user_id: 'demo-zara',
    title: 'Rental clothing platform for special occasions in Germany',
    description: 'Germans buy an outfit for one wedding and never wear it again. We run rental logistics for formal wear with same-day delivery in 5 cities. 2,400 rentals, NPS 71, 34% repeat rate within 6 months. Need marketing to scale.',
    role_category: 'marketing',
    stage: 'revenue',
    compensation_type: 'both',
    equity_percent: 9,
    is_active: true,
    created_at: h(62),
    updated_at: h(62),
    profiles: P.zara,
  },
  {
    id: 'demo-36',
    user_id: 'demo-leon',
    title: 'AI-generated renovation estimates from a single photo',
    description: 'You take a photo of your bathroom, tell us what you want and get a €±15% accurate renovation quote in 90 seconds without a tradesperson visit. 5,000 estimates generated, 12% conversion to actual renovation bookings. Need backend developer.',
    role_category: 'developer',
    stage: 'mvp',
    compensation_type: 'equity',
    equity_percent: 16,
    is_active: true,
    created_at: h(70),
    updated_at: h(70),
    seeks_investment: true,
    investment_round: 'seed',
    profiles: P.leon,
  },
  {
    id: 'demo-37',
    user_id: 'demo-meiLing',
    title: 'Sleep coaching for founders who treat burnout as a badge of honor',
    description: 'We tracked sleep data from 400 founders for 6 months. The ones sleeping less than 6 hours made 30% worse decisions by their own evaluation. Building a coaching product that uses wearable data to make the business case for sleep. Need a developer.',
    role_category: 'developer',
    stage: 'idea',
    compensation_type: 'equity',
    equity_percent: 25,
    is_active: true,
    created_at: h(75),
    updated_at: h(75),
    profiles: P.meiLing,
  },
  {
    id: 'demo-38',
    user_id: 'demo-sven',
    title: 'Customer success platform for B2B SaaS that actually works',
    description: 'Churn happens 60 days before the renewal. Every CS tool shows you the data after it\'s too late. We built early warning models trained on 200k SaaS customer journeys. Customers reduce churn 23% on average. €80k ARR, 18 months old. Want a co-founder.',
    role_category: 'cofounder',
    stage: 'revenue',
    compensation_type: 'equity',
    equity_percent: 35,
    is_active: true,
    created_at: h(85),
    updated_at: h(85),
    profiles: P.sven,
  },
  {
    id: 'demo-39',
    user_id: 'demo-lena',
    title: 'Mental health check-ins embedded in productivity tools',
    description: 'Nobody opens a mental health app when they\'re struggling — they open Notion or Linear. We built integrations that insert 30-second check-ins into the tools people already use. 6k users across 40 companies. HR teams paying €8/user/month.',
    role_category: 'sales',
    stage: 'revenue',
    compensation_type: 'both',
    equity_percent: 8,
    is_active: true,
    created_at: h(90),
    updated_at: h(90),
    profiles: P.lena,
  },
  {
    id: 'demo-40',
    user_id: 'demo-carlos',
    title: 'Verified review platform where only buyers can review',
    description: 'Every review platform is gamed. We verify purchasers via bank transaction data before they can review. 40k verified reviews, 0 incentivized. E-commerce shops pay €199/month because their conversion went up 18%. Need a growth co-founder.',
    role_category: 'cofounder',
    stage: 'revenue',
    compensation_type: 'equity',
    equity_percent: 20,
    is_active: true,
    created_at: h(96),
    updated_at: h(96),
    seeks_investment: true,
    investment_round: 'series-a',
    profiles: P.carlos,
  },
  {
    id: 'demo-41',
    user_id: 'demo-amara',
    title: 'Remote patient monitoring for chronic disease management',
    description: 'Diabetics visit their doctor 4 times a year for 15 minutes. In between, nothing. We connect wearables to a care coordination platform so GPs can see when patients need intervention before it becomes an emergency. 8 GP practices live, €60k ARR.',
    role_category: 'developer',
    stage: 'revenue',
    compensation_type: 'both',
    equity_percent: 12,
    is_active: true,
    created_at: h(100),
    updated_at: h(100),
    seeks_investment: true,
    investment_round: 'seed',
    profiles: P.amara,
  },
  {
    id: 'demo-42',
    user_id: 'demo-bjorn',
    title: 'Visa application tracker for highly skilled migrants',
    description: 'German Fachkräftemangel is real. The visa process is a black box. We map every document required for every visa type, track application status and send alerts when something is missing. 4,200 applicants used it. Employers paying for premium tracking.',
    role_category: 'marketing',
    stage: 'mvp',
    compensation_type: 'both',
    equity_percent: 10,
    is_active: true,
    created_at: h(108),
    updated_at: h(108),
    profiles: P.bjorn,
  },
  {
    id: 'demo-43',
    user_id: 'demo-priya',
    title: 'Competitive intelligence tool for B2B SaaS that doesn\'t need spies',
    description: 'We aggregate public signals — job postings, pricing pages, G2 reviews, LinkedIn activity — to give you a live competitive picture. 250 SaaS companies paying €290/month. Sequoia portfolio company told their entire portfolio about us. Need a sales hire.',
    role_category: 'sales',
    stage: 'revenue',
    compensation_type: 'both',
    equity_percent: 7,
    is_active: true,
    created_at: h(115),
    updated_at: h(115),
    profiles: P.priya,
  },
  {
    id: 'demo-44',
    user_id: 'demo-meiLing',
    title: 'AI procurement assistant for SMEs who overpay for everything',
    description: 'A 50-person company spends €800k/year on tools, services and supplies. Nobody has time to benchmark prices. We audit spend automatically and surface 15-25% savings on average. Paid by results — 20% of savings. 30 SMEs, €340k saved. Need a developer.',
    role_category: 'developer',
    stage: 'revenue',
    compensation_type: 'both',
    equity_percent: 13,
    is_active: true,
    created_at: h(122),
    updated_at: h(122),
    profiles: P.meiLing,
  },
  {
    id: 'demo-45',
    user_id: 'demo-kofi',
    title: 'Event staffing platform — Eventbrite but for the people who run the event',
    description: 'Events need 50 staff with 2 weeks notice. Nobody has a system for this. We built a marketplace that verifies, schedules and pays event staff. €180k GMV in first 6 months, mostly Berlin and Frankfurt. Want a co-founder with operations experience.',
    role_category: 'cofounder',
    stage: 'revenue',
    compensation_type: 'equity',
    equity_percent: 25,
    is_active: true,
    created_at: h(130),
    updated_at: h(130),
    profiles: P.kofi,
  },
  {
    id: 'demo-46',
    user_id: 'demo-felix',
    title: 'Database change management for teams who are scared of migrations',
    description: 'Every startup has a database they\'re afraid to touch. We built a tool that generates migration scripts, simulates them on a clone of your production DB and rolls back automatically if something breaks. 800 dev teams, €49/month. Need a designer.',
    role_category: 'designer',
    stage: 'revenue',
    compensation_type: 'both',
    equity_percent: 8,
    is_active: true,
    created_at: h(138),
    updated_at: h(138),
    profiles: P.felix,
  },
  {
    id: 'demo-47',
    user_id: 'demo-nina',
    title: 'Corporate carbon reporting that doesn\'t take 3 months to prepare',
    description: 'CSRD requires Scope 1, 2 and 3 reporting from 2025. Consultants charge €40k to prepare it. We automate 80% of the data collection from existing ERP systems and generate audit-ready reports. 25 mid-size companies in beta. Need a co-founder.',
    role_category: 'cofounder',
    stage: 'mvp',
    compensation_type: 'equity',
    equity_percent: 30,
    is_active: true,
    created_at: h(145),
    updated_at: h(145),
    seeks_investment: true,
    investment_round: 'seed',
    profiles: P.nina,
  },
  {
    id: 'demo-48',
    user_id: 'demo-thomas',
    title: 'Corporate training platform that employees actually use',
    description: 'Compliance training completion rates average 34%. Nobody cares. We built 5-minute micro-learning modules with spaced repetition that feel like news, not HR. 12 companies, 4,200 employees, 89% completion. Need a backend engineer.',
    role_category: 'developer',
    stage: 'revenue',
    compensation_type: 'both',
    equity_percent: 11,
    is_active: true,
    created_at: h(155),
    updated_at: h(155),
    profiles: P.thomas,
  },
  {
    id: 'demo-49',
    user_id: 'demo-zara',
    title: 'B2B platform for textile waste exchange between manufacturers',
    description: 'A shirt manufacturer has 3 tons of cotton offcuts. A bag maker needs exactly that. Nobody knows the other exists. We built a marketplace for industrial textile waste. 80 manufacturers, €420k in transactions, 340 tons diverted from landfill. Need growth.',
    role_category: 'marketing',
    stage: 'revenue',
    compensation_type: 'both',
    equity_percent: 9,
    is_active: true,
    created_at: h(162),
    updated_at: h(162),
    profiles: P.zara,
  },
  {
    id: 'demo-50',
    user_id: 'demo-leon',
    title: 'PropTech for social housing allocation — fair by algorithm',
    description: 'Social housing allocation in Germany is opaque, slow and full of errors. We built a transparent scoring and matching system for municipalities. 3 city districts live. Waiting time reduced from 18 to 11 months average. Need a backend co-founder.',
    role_category: 'cofounder',
    stage: 'mvp',
    compensation_type: 'equity',
    equity_percent: 28,
    is_active: true,
    created_at: h(170),
    updated_at: h(170),
    seeks_investment: true,
    investment_round: 'seed',
    profiles: P.leon,
  },
]
