import type { Listing, Profile } from '@/types'

const now = Date.now()
const h = (n: number) => new Date(now - n * 3600000).toISOString()

export const DEMO_PROFILES: Profile[] = []

const P: Record<string, Profile> = {
  meiLing: {
    id: 'demo-mei',
    username: 'meilingc',
    full_name: 'Mei-Ling C.',
    bio: 'Ex-McKinsey Beraterin die irgendwann aufgehört hat zu fragen ob der Markt groß genug ist. Baue jetzt Scheiß den ich selbst benutzen würde.',
    avatar_url: null,
    skills: ['AI/ML', 'B2C', 'Produktstrategie'],
    location: 'Berlin',
    created_at: h(720),
  },
  tariq: {
    id: 'demo-tariq',
    username: 'tariqb',
    full_name: 'Tariq B.',
    bio: 'Dropout aus 3 Hochschulen, 0 Exits, unendlich Energie. Meine Oma sagt ich soll endlich einen richtigen Job suchen. Sie hat unrecht.',
    avatar_url: null,
    skills: ['Web3', 'Mobile', 'Chaos-Engineering'],
    location: 'Hamburg',
    created_at: h(600),
  },
  anastasia: {
    id: 'demo-ana',
    username: 'anastasiak',
    full_name: 'Anastasia K.',
    bio: '15 Jahre Unternehmensberatung und ich hab nichts gelernt außer pitchen. Jetzt lerne ich das echte Leben.',
    avatar_url: null,
    skills: ['Operations', 'Enterprise Sales', 'Buzzwords'],
    location: 'München',
    created_at: h(800),
  },
  kofi: {
    id: 'demo-kofi',
    username: 'kofia',
    full_name: 'Kofi A.',
    bio: 'Serial Pivot Artist. Letzte drei Pivots: Metaverse-Hundesalon → NFT-Bäckerei → jetzt das hier. Diesmal wird es anders.',
    avatar_url: null,
    skills: ['Fundraising', 'Pitching', 'Pivoting'],
    location: 'Frankfurt',
    created_at: h(400),
  },
  carlos: {
    id: 'demo-carlos',
    username: 'carlosr',
    full_name: 'Carlos R.',
    bio: 'Ich dachte ich erfinde das nächste Uber. Es war eine App für Igel. Dieses Mal ist es aber wirklich das nächste Uber.',
    avatar_url: null,
    skills: ['Marketplace', 'Growth', 'VC-Blinddate'],
    location: 'Zürich',
    created_at: h(500),
  },
  yuki: {
    id: 'demo-yuki',
    username: 'yukit',
    full_name: 'Yuki T.',
    bio: 'FOMO-getriebener Builder mit ADHS. Diese Woche meine 4. Startup-Idee, letzte Woche 3. Wir finden schon eine.',
    avatar_url: null,
    skills: ['React Native', 'Rapid Prototyping', 'Schlafmangel'],
    location: 'Remote',
    created_at: h(350),
  },
  lena: {
    id: 'demo-lena',
    username: 'lenam',
    full_name: 'Lena M.',
    bio: 'Psychologin die zu viel Twilight gelesen hat und jetzt eine KI für emotionale Unterstützung baut. Ja, wirklich.',
    avatar_url: null,
    skills: ['Psychologie', 'UX Research', 'Empathie-as-a-Service'],
    location: 'Leipzig',
    created_at: h(480),
  },
  felix: {
    id: 'demo-felix',
    username: 'felixw',
    full_name: 'Felix W.',
    bio: 'Backend-Engineer der nach 8 Jahren Google-Gehalt endlich etwas Sinnvolles bauen will. Oder zumindest etwas Lustiges.',
    avatar_url: null,
    skills: ['Go', 'Kubernetes', 'Existenzkrise'],
    location: 'Berlin',
    created_at: h(200),
  },
  priya: {
    id: 'demo-priya',
    username: 'priyad',
    full_name: 'Priya D.',
    bio: 'Product Lead bei einem Unicorn das niemand mag. Baue nebenbei das was ich eigentlich bauen will.',
    avatar_url: null,
    skills: ['Product', 'User Research', 'Internes Leiden'],
    location: 'Düsseldorf',
    created_at: h(300),
  },
  bjorn: {
    id: 'demo-bjorn',
    username: 'bjornl',
    full_name: 'Björn L.',
    bio: 'Schwede in Deutschland. Kommt nicht klar mit der Bürokratie, baut deswegen Software dagegen.',
    avatar_url: null,
    skills: ['FinTech', 'Compliance', 'Sarkasmus'],
    location: 'Stuttgart',
    created_at: h(250),
  },
  amara: {
    id: 'demo-amara',
    username: 'amarao',
    full_name: 'Amara O.',
    bio: 'Ärztin die gemerkt hat dass das Gesundheitssystem kaputt ist und beschlossen hat, als Gründerin daran zu scheitern statt als Ärztin.',
    avatar_url: null,
    skills: ['HealthTech', 'Medizin', 'Systemkritik'],
    location: 'Köln',
    created_at: h(380),
  },
  sven: {
    id: 'demo-sven',
    username: 'svenkr',
    full_name: 'Sven K.',
    bio: 'Hat drei Startups gegründet. Zwei sind tot, eines lebt irgendwie noch. Ratio ist okay.',
    avatar_url: null,
    skills: ['B2B SaaS', 'Customer Success', 'Resilienz'],
    location: 'Hamburg',
    created_at: h(550),
  },
}

Object.values(P).forEach(p => DEMO_PROFILES.push(p))

type DemoListing = Omit<Listing, 'profiles'> & {
  profiles: Profile
  seeks_investment?: boolean
  investment_round?: string
}

export const DEMO_LISTINGS: DemoListing[] = [
  {
    id: 'demo-1',
    user_id: 'demo-mei',
    title: 'Tinder für Mittagspausen — weil auch Introvertierte essen müssen',
    description: 'Matching-Algorithmus für Büroangestellte die mittags nicht alleine essen wollen aber auch keine Smalltalk-Energie haben. KI wählt aus wer kompatibel schweigen kann. 340 Beta-User, 12% Conversion zu echten Treffen. Rest hat einfach alleine gegessen. Das ist auch okay.',
    role_category: 'developer',
    stage: 'mvp',
    compensation_type: 'equity',
    equity_percent: 12,
    is_active: true,
    created_at: h(1),
    updated_at: h(1),
    profiles: P.meiLing,
  },
  {
    id: 'demo-2',
    user_id: 'demo-tariq',
    title: 'Blockchain für Schrebergarten-Wartelisten',
    description: 'In deutschen Städten wartet man 15–25 Jahre auf einen Schrebergarten. Wir tokenisieren Warteplätze als NFTs — handelbar, beleihbar, vererbbar. Klingt bescheuert. 400 Leute auf unserer eigenen Warteliste. Suche CTO der das nicht sofort ablehnt.',
    role_category: 'cofounder',
    stage: 'idea',
    compensation_type: 'equity',
    equity_percent: 30,
    is_active: true,
    created_at: h(2),
    updated_at: h(2),
    seeks_investment: true,
    investment_round: 'pre-seed',
    profiles: P.tariq,
  },
  {
    id: 'demo-3',
    user_id: 'demo-ana',
    title: 'SaaS-CRM für Astrologen',
    description: 'Es gibt 180.000 aktive Astrologen in der DACH-Region. Keiner hat ein ordentliches Buchungstool. Wir bauen HubSpot aber für Leute die Saturn-Retrograde als Ausrede für alles benutzen. MRR: €8.400. Suche Designer der den Vibe versteht.',
    role_category: 'designer',
    stage: 'revenue',
    compensation_type: 'both',
    equity_percent: 7,
    is_active: true,
    created_at: h(3),
    updated_at: h(3),
    profiles: P.anastasia,
  },
  {
    id: 'demo-4',
    user_id: 'demo-kofi',
    title: 'Uber aber nur für Omas zum Arzt',
    description: 'Meine Oma kommt nicht zur Chemo weil kein Taxi da ist und sie kein Uber kann. Pilot in Frankfurt: 60 Omas, 94% wollen wiederkommen. Suche Mitgründer mit Mobilität-Background oder wenigstens Empathie.',
    role_category: 'cofounder',
    stage: 'mvp',
    compensation_type: 'equity',
    equity_percent: 20,
    is_active: true,
    created_at: h(4),
    updated_at: h(4),
    seeks_investment: true,
    investment_round: 'seed',
    profiles: P.kofi,
  },
  {
    id: 'demo-5',
    user_id: 'demo-carlos',
    title: 'KI generiert Entschuldigungen für alle Lebenslagen',
    description: 'GPT-4 generiert überzeugende Entschuldigungen für: zu spät kommen, Geburtstage vergessen, WhatsApp ignorieren, nicht zum Sport gehen und den Chef anlügen. 50k Downloads, 4.8 Sterne. "Lebensrettend" — App Store Review. Suche Growth Hacker der genauso wenig Scham hat wie wir.',
    role_category: 'marketing',
    stage: 'revenue',
    compensation_type: 'both',
    equity_percent: 9,
    is_active: true,
    created_at: h(5),
    updated_at: h(5),
    profiles: P.carlos,
  },
  {
    id: 'demo-6',
    user_id: 'demo-yuki',
    title: 'RentTok — TikTok für Rentner, Schriftgröße 24, kein Algorithmus-Stress',
    description: 'Meine Oma hat 4 Stunden gebraucht um TikTok zu verstehen. Wir bauen dasselbe aber ohne Content der nach 21 Uhr noch pushed. 200 Beta-Omas. Eine hat gesagt "besser als Fernsehen". Wir verwenden das als Testimonial.',
    role_category: 'developer',
    stage: 'mvp',
    compensation_type: 'equity',
    equity_percent: 18,
    is_active: true,
    created_at: h(7),
    updated_at: h(7),
    profiles: P.yuki,
  },
  {
    id: 'demo-7',
    user_id: 'demo-lena',
    title: 'Therapie-App für Gründer die ihrem eigenen Pitch glauben',
    description: 'CBT kombiniert mit Realitäts-Checks für Founder-Brains. Modul 1: "Nein, deine Idee ist nicht das nächste Google." Modul 2: "Dein Investor-Update ist kein Erfolg." 1.200 Gründer auf Warteliste. Brauche Backend-Dev der vielleicht selbst Therapie gebrauchen könnte.',
    role_category: 'developer',
    stage: 'idea',
    compensation_type: 'equity',
    equity_percent: 22,
    is_active: true,
    created_at: h(9),
    updated_at: h(9),
    profiles: P.lena,
  },
  {
    id: 'demo-8',
    user_id: 'demo-tariq',
    title: 'DAO für Kleingärtner — endlich DeFi für das Boomer-Segment',
    description: 'Kleingärtnervereine haben collective €2.3Mrd in Grundstücken aber null digitale Infrastruktur. Token-Voting für "Wer darf Lauch neben Tomaten pflanzen"-Entscheidungen. Pilot mit 3 Vereinen. Suche jemanden der sowohl Solidity als auch Gartenrecht versteht.',
    role_category: 'cofounder',
    stage: 'mvp',
    compensation_type: 'equity',
    equity_percent: 25,
    is_active: true,
    created_at: h(11),
    updated_at: h(11),
    seeks_investment: true,
    investment_round: 'pre-seed',
    profiles: P.tariq,
  },
  {
    id: 'demo-9',
    user_id: 'demo-ana',
    title: 'B2B-API für Behördenformulare — Stripe für den Amtsschimmel',
    description: 'Alle deutschen Verwaltungsformulare als API. Klingt boring. €40k MRR nach 8 Monaten, kein Marketing. Enterprise-Kunden zahlen weil sie keine Alternative haben. Suche Sales-Person die Bürokratie nicht hasst.',
    role_category: 'sales',
    stage: 'revenue',
    compensation_type: 'both',
    equity_percent: 8,
    is_active: true,
    created_at: h(14),
    updated_at: h(14),
    profiles: P.anastasia,
  },
  {
    id: 'demo-10',
    user_id: 'demo-felix',
    title: 'Duolingo aber für Steuererklärungen',
    description: '5-Minuten-Lektionen die erklären was eine GWG ist, warum man Bürostuhl absetzen kann und was zum Teufel eine "außergewöhnliche Belastung" bedeutet. 15k User, 40% machen ihre Steuern jetzt selbst. DATEV findet uns nicht lustig. Das ist ein gutes Zeichen.',
    role_category: 'marketing',
    stage: 'mvp',
    compensation_type: 'both',
    equity_percent: 10,
    is_active: true,
    created_at: h(16),
    updated_at: h(16),
    profiles: P.felix,
  },
  {
    id: 'demo-11',
    user_id: 'demo-priya',
    title: 'Anonymous-Glassdoor aber für Gründer über ihre Investoren',
    description: 'Investoren können alles über Startups lesen aber Gründer können nicht lesen welcher VC 6 Monate braucht um abzusagen. Wir bauen das. 800 verifizierte Reviews in der Beta. Kein einziger VC hat sich beschwert weil sie es noch nicht gefunden haben.',
    role_category: 'developer',
    stage: 'mvp',
    compensation_type: 'equity',
    equity_percent: 15,
    is_active: true,
    created_at: h(20),
    updated_at: h(20),
    profiles: P.priya,
  },
  {
    id: 'demo-12',
    user_id: 'demo-bjorn',
    title: 'AI-Assistent der deutsche Behördensprache in Deutsch übersetzt',
    description: 'Ein Mahnbescheid ist kein Bescheid über Mahner. Wir übersetzen Amtsdeutsch in Sprache die Menschen verstehen, in Echtzeit per Browser-Extension. 12k aktive User. Zuständige Ministerien haben Fragen gestellt. Wir haben höflich geantwortet.',
    role_category: 'cofounder',
    stage: 'mvp',
    compensation_type: 'equity',
    equity_percent: 30,
    is_active: true,
    created_at: h(24),
    updated_at: h(24),
    profiles: P.bjorn,
  },
  {
    id: 'demo-13',
    user_id: 'demo-amara',
    title: 'Wartezeit-Killer für Arztpraxen — Tetris für das Wartezimmer',
    description: 'Patienten warten im Schnitt 43 Minuten. Wir ersetzen die Zeitschriften von 2019 durch ein Tablet mit echten Aufklärungsvideos, Vorsorge-Checklisten und Spielen. 25 Praxen im Piloten. Ärzte sagen "endlich". Patienten sagen "ach schon dran". Suche Developer.',
    role_category: 'developer',
    stage: 'mvp',
    compensation_type: 'both',
    equity_percent: 13,
    is_active: true,
    created_at: h(30),
    updated_at: h(30),
    seeks_investment: true,
    investment_round: 'seed',
    profiles: P.amara,
  },
  {
    id: 'demo-14',
    user_id: 'demo-sven',
    title: 'Slack aber für Handwerksbetriebe — kein Englisch, keine Threads',
    description: 'Mein Vater ist Elektriker. Er benutzt WhatsApp für alles inklusive Angebote und Reklamationen. Wir bauen eine App die aussieht wie WhatsApp aber DSGVO-konform ist und Angebote, Protokolle und Stundenzettel hat. 40 Betriebe zahlen bereits.',
    role_category: 'cofounder',
    stage: 'revenue',
    compensation_type: 'equity',
    equity_percent: 20,
    is_active: true,
    created_at: h(36),
    updated_at: h(36),
    profiles: P.sven,
  },
  {
    id: 'demo-15',
    user_id: 'demo-felix',
    title: 'Automated Code Review für das Finanzamt',
    description: 'Wir verarbeiten ELSTER-Exports und finden automatisch Fehler, vergessene Absetzungen und Stellen wo man legal Geld sparen kann. Closed Beta, 200 Steuerberater. Suche jemanden der nicht aufhört wenn er "Datenschutz" hört sondern anfängt.',
    role_category: 'designer',
    stage: 'idea',
    compensation_type: 'equity',
    equity_percent: 17,
    is_active: true,
    created_at: h(42),
    updated_at: h(42),
    profiles: P.felix,
  },
  {
    id: 'demo-16',
    user_id: 'demo-kofi',
    title: 'On-Demand Lagerraum für Berliner ohne Keller',
    description: 'Airbnb für Kellerspeicher. Berliner Altbauten haben keinen Keller. Berliner haben zu viel Zeug. Wir matchen beides. 180 aktive Listings in Berlin, 60% Auslastung. Suche Marketing-Person die erklärt warum das nicht weird ist.',
    role_category: 'marketing',
    stage: 'mvp',
    compensation_type: 'both',
    equity_percent: 11,
    is_active: true,
    created_at: h(48),
    updated_at: h(48),
    profiles: P.kofi,
  },
  {
    id: 'demo-17',
    user_id: 'demo-priya',
    title: 'KI-Coach der dir sagt wann du aufhören sollst zu arbeiten',
    description: 'Nicht ein weiterer Produktivitäts-App. Der gegenteil davon. Erkennt Burnout-Muster aus Kalender + Slack-Activity und schickt dir um 18:30 Uhr eine Nachricht: "Jetzt aufhören." 3.000 User, 22% weniger Überstunden laut Self-Report. HR-Teams finden das beunruhigend.',
    role_category: 'developer',
    stage: 'mvp',
    compensation_type: 'equity',
    equity_percent: 14,
    is_active: true,
    created_at: h(55),
    updated_at: h(55),
    profiles: P.priya,
  },
  {
    id: 'demo-18',
    user_id: 'demo-yuki',
    title: 'Fiverr aber nur für Dinge die Rentner können',
    description: 'Marktplatz für Fähigkeiten über 65: Schreibmaschine reparieren, Sütterlin lesen, echtes Brot backen, Steuerformulare ohne Software ausfüllen. Ironie: wird von Gen Z am meisten genutzt. 420 aktive Anbieter. Suche Mitgründer der das ernst nehmen kann ohne zu lachen.',
    role_category: 'cofounder',
    stage: 'mvp',
    compensation_type: 'equity',
    equity_percent: 28,
    is_active: true,
    created_at: h(65),
    updated_at: h(65),
    profiles: P.yuki,
  },
  {
    id: 'demo-19',
    user_id: 'demo-bjorn',
    title: 'Tinder für Steuerberater und Freiberufler',
    description: 'Den richtigen Steuerberater finden ist wie Dating. Profil-Matching nach Branche, Kommunikationsstil und ob man WhatsApp oder E-Mail bevorzugt. 2.000 erfolgreiche Matches. 0 Klagen bisher. Suche Backend-Person.',
    role_category: 'developer',
    stage: 'revenue',
    compensation_type: 'both',
    equity_percent: 6,
    is_active: true,
    created_at: h(72),
    updated_at: h(72),
    profiles: P.bjorn,
  },
  {
    id: 'demo-20',
    user_id: 'demo-amara',
    title: 'Health-Tracking das nicht so tut als wärst du ein Athlet',
    description: 'Alle Fitness-Apps gehen davon aus dass du 10.000 Schritte machst und um 6 Uhr aufstehst. Wir tracken ob du deine Wasserflasche getrunken hast, heute draußen warst und nicht vier Stunden auf TikTok. Pilot: 800 User mit explizit niedrigen Zielen. 67% fühlen sich besser.',
    role_category: 'designer',
    stage: 'mvp',
    compensation_type: 'equity',
    equity_percent: 16,
    is_active: true,
    created_at: h(80),
    updated_at: h(80),
    profiles: P.amara,
  },
]
